version: "3.8"
services:
  wg-easy:
    image: wg-easy
    command: npm run serve
    volumes:
      - ./src/:/app/
    ports:
      - "51822:51822/udp"
      - "51821:51821/tcp"
    environment: 
      # - PASSWORD=p
      - WG_HOST=127.0.0.1
      - WG_PORT=51822
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
